name: dreamspace_ai
description: "An AI-powered interior design stylist."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.7
  http: ^1.2.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  
  # New package to open URLs in a browser
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
